surveyproj/survey/urls.py
from django.conf.urls import url

from . import views

app_name = 'survey'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^manage$', views.manage_index, name='manage/index'),
    # url(r'^manage/(?P<question_id>[0-9]+)/edit$', views.manage_edit, name='manage/edit'),
    url(r'^manage/new$', views.manage_new, name='manage/new'),
]

surveyproj/surveyproj/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from django.contrib.auth.views import login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import reverse

urlpatterns = [
    url(r'^$', lambda _: HttpResponseRedirect(reverse('survey:index'))),
    url(r'^surveys/', include('survey.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', auth.views.login, name='login'),
    url(r'^accounts/logout/$', auth.views.logout, name='logout'),
]

surveyproj/survey/models.py
from django.db import models
from django.utils import timezone


class BaseModel(models.Model):
    """
    Mixin with created-, updated-at datetimes.
    """
    class Meta:
        abstract = True

    created_at = models.DateTimeField('datetime created', auto_now_add=True)
    updated_at = models.DateTimeField('datetime updated', auto_now=True)


class Question(BaseModel):
    """
    Survey question.
    """
    published_at = models.DateTimeField('datetime published', blank=True, null=True)
    text = models.CharField('question text', max_length=500)

    def is_published(self):
        return self.published_at and self.published_at < timezone.now()

    def total_votes(self):
        return sum([a.votes for a in self.answer_set.all()])

    def __str__(self):
        return self.text


class Answer(BaseModel):
    """
    One of multiple-choice answers to a survey question.
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField('answer text', max_length=500)
    votes = models.IntegerField(default=0)

    def percent_vote(self):
        return 100 * self.votes / self.question.total_votes()

    def __str__(self):
        return self.text


class Response(BaseModel):
    """
    Survey answer
    """
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer.text

surveyproj/survey/forms.py
from django import forms
from django.utils import timezone


class QuestionForm(forms.Form):
    question_text = forms.CharField()
    published_at = forms.DateTimeField(initial=timezone.now)


class AnswerForm(forms.Form):
    answer_text = forms.CharField()

surveyproj/survey/views.py
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render, reverse
from django.utils import timezone
import random

from survey.forms import AnswerForm, QuestionForm
from survey.models import Answer, Response, Question


def index(request):
    """
    Return random survey question not answered by the requesting session.
    """
    answered = request.session.get('answered_questions', [])
    qry = Question.objects.filter(published_at__lte=timezone.now()).exclude(id__in=answered)
    return render(request, 'survey/index.html', {
        'question': qry.all()[random.randrange(qry.count())] if qry.count() else None,
        # 'error_message': 'Hold your horses..!'
    })


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if not question.is_published() and request.user.is_superuser:
        raise Http404('Unable to find this question.')
    ctx = {
        'question': question,
        'recent_responses': Response.objects.select_related('answer').filter(answer__question=question_id)
                                            .order_by('-created_at')[:20],
    }
    return render(request, 'survey/results.html', ctx)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        answer = question.answer_set.get(pk=request.POST['answer'])
        answer.votes += 1
        answer.save()
        rsp = Response(answer=answer)
        rsp.save()
        answered = request.session.get('answered_questions', [])
        answered += [question.id]
        request.session['answered_questions'] = answered
        return HttpResponseRedirect(reverse('survey:results', args=(question.id,)))
    except (KeyError, Answer.DoesNotExist):
        return render(request, 'survey/detail.html', {
            'question': question,
            'error_message': 'You didn\'t select a choice.',
        })


@login_required
def manage_index(request):
    return render(request, 'survey/manage/index.html', {
        'questions': Question.objects.order_by('-updated_at').all()[:50],
    })


@login_required
def manage_new(request):
    answer_formset = formset_factory(AnswerForm, extra=3, max_num=10)
    if request.method == 'POST':
        qf = QuestionForm(request.POST)
        afs = answer_formset(request.POST)
        if qf.is_valid() and afs.is_valid():
            q = Question(text=qf.cleaned_data['question_text'], published_at=qf.cleaned_data['published_at'])
            q.save()
            for f in afs:
                ans = Answer(text=f.cleaned_data['answer_text'], question=q)
                ans.save()
            return HttpResponseRedirect(reverse('survey:manage/index'))
    else:
        fs = answer_formset()
    return render(request, 'survey/manage/new.html', {
        'question_form': QuestionForm(),
        'answer_formset': fs,
    })


# @login_required
# def manage_edit(request, question_id):
#     return render(request, 'survey/manage/edit.html', {
#         'question': Question.objects.get(pk=question_id),
#     })

surveyproj/survey/templates/survey/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>SumoSurvey</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Load up jQuery, Bulma styles, and Google Montserrat font -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.0/css/bulma.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'survey/css/base.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar" role="navigation">
            <div class="navbar-end">
                <a class="navbar-item " href="{% url 'survey:index' %}">Home</a>
                <a class="navbar-item " href="{% url 'survey:manage/index' %}">Manage</a>
            </div>
        </nav>
    </div>
    <section class="hero is-primary is-bold">
        <!-- <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div class="navbar-menu">
                        <div class="navbar-end">
                            <a class="navbar-item">Home</a>
                            <a class="navbar-item">Manage</a>
                        </div>
                    </div>
                </div>
            </nav>
        </div> -->
        <div class="hero-body">
            <div class="container">
              <h1 class="title">SumoSurvey</h1>
              <h2 class="subtitle">Questions for sumos, and other people.</h2>
          </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
        {% if error_message %}
            <div class="notification is-warning">{{ error_message }}</div>
        {% endif %}
        {% block content %}
        {% endblock %}
        </div>
    </section>
</body>
</html>

surveyproj/survey/templates/survey/detail.html
{% extends 'survey/base.html' %}

{% block content %}
    <h1>{{ question.text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'survey:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for answer in question.answer_set.all %}
        <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
        <label for="answer{{ forloop.counter }}">{{ answer.text }}</label><br />
    {% endfor %}
        <input type="submit" value="Vote" />
    </form>
{% endblock %}

surveyproj/survey/templates/survey/index.html
{% extends 'survey/base.html' %}

{% block content %}
<!-- <div class="columns">
    <div class="column is-two-thirds"> -->
    {% if question %}
        <div class="notification is-dark">
            <p>Published {{ question.published_at | date:"SHORT_DATE_FORMAT" }}</p>
            <h3 class="title">{{ question.text }}</h3>
        </div>
        <script type="text/javascript">
            $(function() {
                $('form.poll input[type=radio]').change(function(e) {
                    var parentControl = $(this).closest('.control');
                    parentControl.siblings('.control').removeClass('checked');
                    parentControl.addClass('checked');
                });
            });
        </script>
        <form class="poll" action="{% url 'survey:vote' question.id %}" method="post">
        {% csrf_token %}
            <div class="field">
            {% for answer in question.answer_set.all %}
                <div class="control">
                    <label class="radio" for="answer{{ forloop.counter }}">
                        <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}">
                        {{ answer.text }}
                    </label>
                </div>
            {% endfor %}
            </div>
            <div class="field is-grouped">
                <p class="control">
                    <button class="button is-primary" type="submit">Vote</button>
                </p>
                <p class="control">
                    <a class="button is-light" href="{% url 'survey:results' question.id %}">View Results</a>
                </p>
            </div>
        </form>
    {% else %}
        <div class="notification is-dark">
            <h3 class="title">¿ɓuıuǝddɐɥ sı ʇɐɥM</h3>
        </div>
        <p>Good grief, you've answered all the questions! Check back later for new stuff...</p>
    {% endif %}
<!--     </div>
    <div class="column">
        <div class="notification is-light">
            <p>Hello, there ;)</p>
        </div>
    </div>
</div> -->
{% endblock %}

surveyproj/survey/templates/survey/results.html
{% extends 'survey/base.html' %}

{% block content %}
<div class="notification is-dark">
    <p>Results for</p>
    <h3 class="title">{{ question.text }}</h3>
</div>
<div class="columns">
    <div class="column is-three-fifths">
      <ul class="poll-results">
      {% for answer in question.answer_set.all %}
          <li class="poll-result">
              <div class="is-pulled-right">{{ answer.votes }} vote{{ answer.votes | pluralize }}</div>
              {{ answer.text }}
              <progress class="progress is-medium is-info" value="{{ answer.percent_vote }}" max="100">{{ answer.percent_vote }}%</progress>
          </li>
      {% endfor %}
      </ul>

      <p class="has-text-centered">
        <br>
        <br>
        <a class="button" href="{% url 'survey:index' %}">Try another survey?</a>
        <br>
        <br>
      </p>
    </div>
    <div class="column">
        <div class="content notification">
            <h4>Recent votes</h4>
            <ul>
            {% for response in recent_responses %}
                <li>Vote for "{{ response }}" at {{ response.created_at }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}